version: '3.7'

networks:
  http_network:
    external: true

services:
  sample-prod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:80'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=http_network"
      - "traefik.http.routers.react.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.services.react.loadbalancer.server.port=80"
    networks:
      - http_network
